export const COLORS = {
  primary: '#DB2777',
  background: '#FDF6F9',
  card: '#FFFFFF',
  textPrimary: '#1F1A1D',
  textSecondary: '#6E5A66',
  textOnPrimary: '#FFFFFF',
  surface: '#FAECF2',
  border: '#F1DCE6',
  shadow: '#1F1A1D',
  warning: '#C97A2B',
  success: '#2E7D5B',
  danger: '#B3261E',
  logo: '#DB2777',
} as const;
